# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_struc', [dirname(__file__)])
        except ImportError:
            import _struc
            return _struc
        if fp is not None:
            try:
                _mod = imp.load_module('_struc', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _struc = swig_import_helper()
    del swig_import_helper
else:
    import _struc
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _struc.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _struc.SwigPyIterator_value(self)
    def incr(self, n=1): return _struc.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _struc.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _struc.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _struc.SwigPyIterator_equal(self, *args)
    def copy(self): return _struc.SwigPyIterator_copy(self)
    def next(self): return _struc.SwigPyIterator_next(self)
    def __next__(self): return _struc.SwigPyIterator___next__(self)
    def previous(self): return _struc.SwigPyIterator_previous(self)
    def advance(self, *args): return _struc.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _struc.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _struc.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _struc.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _struc.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _struc.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _struc.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _struc.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Double_Vector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Double_Vector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Double_Vector, name)
    __repr__ = _swig_repr
    def iterator(self): return _struc.Double_Vector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _struc.Double_Vector___nonzero__(self)
    def __bool__(self): return _struc.Double_Vector___bool__(self)
    def __len__(self): return _struc.Double_Vector___len__(self)
    def pop(self): return _struc.Double_Vector_pop(self)
    def __getslice__(self, *args): return _struc.Double_Vector___getslice__(self, *args)
    def __setslice__(self, *args): return _struc.Double_Vector___setslice__(self, *args)
    def __delslice__(self, *args): return _struc.Double_Vector___delslice__(self, *args)
    def __delitem__(self, *args): return _struc.Double_Vector___delitem__(self, *args)
    def __getitem__(self, *args): return _struc.Double_Vector___getitem__(self, *args)
    def __setitem__(self, *args): return _struc.Double_Vector___setitem__(self, *args)
    def append(self, *args): return _struc.Double_Vector_append(self, *args)
    def empty(self): return _struc.Double_Vector_empty(self)
    def size(self): return _struc.Double_Vector_size(self)
    def clear(self): return _struc.Double_Vector_clear(self)
    def swap(self, *args): return _struc.Double_Vector_swap(self, *args)
    def get_allocator(self): return _struc.Double_Vector_get_allocator(self)
    def begin(self): return _struc.Double_Vector_begin(self)
    def end(self): return _struc.Double_Vector_end(self)
    def rbegin(self): return _struc.Double_Vector_rbegin(self)
    def rend(self): return _struc.Double_Vector_rend(self)
    def pop_back(self): return _struc.Double_Vector_pop_back(self)
    def erase(self, *args): return _struc.Double_Vector_erase(self, *args)
    def __init__(self, *args): 
        this = _struc.new_Double_Vector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _struc.Double_Vector_push_back(self, *args)
    def front(self): return _struc.Double_Vector_front(self)
    def back(self): return _struc.Double_Vector_back(self)
    def assign(self, *args): return _struc.Double_Vector_assign(self, *args)
    def resize(self, *args): return _struc.Double_Vector_resize(self, *args)
    def insert(self, *args): return _struc.Double_Vector_insert(self, *args)
    def reserve(self, *args): return _struc.Double_Vector_reserve(self, *args)
    def capacity(self): return _struc.Double_Vector_capacity(self)
    __swig_destroy__ = _struc.delete_Double_Vector
    __del__ = lambda self : None;
Double_Vector_swigregister = _struc.Double_Vector_swigregister
Double_Vector_swigregister(Double_Vector)

class moments(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, moments, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, moments, name)
    __repr__ = _swig_repr
    __swig_setmethods__["mm1"] = _struc.moments_mm1_set
    __swig_getmethods__["mm1"] = _struc.moments_mm1_get
    if _newclass:mm1 = _swig_property(_struc.moments_mm1_get, _struc.moments_mm1_set)
    __swig_setmethods__["mm2"] = _struc.moments_mm2_set
    __swig_getmethods__["mm2"] = _struc.moments_mm2_get
    if _newclass:mm2 = _swig_property(_struc.moments_mm2_get, _struc.moments_mm2_set)
    __swig_setmethods__["mm3"] = _struc.moments_mm3_set
    __swig_getmethods__["mm3"] = _struc.moments_mm3_get
    if _newclass:mm3 = _swig_property(_struc.moments_mm3_get, _struc.moments_mm3_set)
    __swig_setmethods__["mm4"] = _struc.moments_mm4_set
    __swig_getmethods__["mm4"] = _struc.moments_mm4_get
    if _newclass:mm4 = _swig_property(_struc.moments_mm4_get, _struc.moments_mm4_set)
    __swig_setmethods__["mm5"] = _struc.moments_mm5_set
    __swig_getmethods__["mm5"] = _struc.moments_mm5_get
    if _newclass:mm5 = _swig_property(_struc.moments_mm5_get, _struc.moments_mm5_set)
    __swig_setmethods__["mm6"] = _struc.moments_mm6_set
    __swig_getmethods__["mm6"] = _struc.moments_mm6_get
    if _newclass:mm6 = _swig_property(_struc.moments_mm6_get, _struc.moments_mm6_set)
    def __init__(self): 
        this = _struc.new_moments()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _struc.delete_moments
    __del__ = lambda self : None;
moments_swigregister = _struc.moments_swigregister
moments_swigregister(moments)


def moments_cal(*args):
  return _struc.moments_cal(*args)
moments_cal = _struc.moments_cal

def print_angles(*args):
  return _struc.print_angles(*args)
print_angles = _struc.print_angles

def print_vels(*args):
  return _struc.print_vels(*args)
print_vels = _struc.print_vels

def print_accs(*args):
  return _struc.print_accs(*args)
print_accs = _struc.print_accs
# This file is compatible with both classic and new-style classes.


