#!/usr/bin/python
import sys
sys.path.append('/home/hiep/Desktop/linuxcnc_dynamics')

import struc

import hal, time
h = hal.component("inversedynamics")

#Input joint position
h.newpin("pos1", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("pos2", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("pos3", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("pos4", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("pos5", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("pos6", hal.HAL_FLOAT, hal.HAL_IN)

#Input joint vel
h.newpin("vel1", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("vel2", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("vel3", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("vel4", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("vel5", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("vel6", hal.HAL_FLOAT, hal.HAL_IN)

#Input joint acc
h.newpin("acc1", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("acc2", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("acc3", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("acc4", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("acc5", hal.HAL_FLOAT, hal.HAL_IN)
h.newpin("acc6", hal.HAL_FLOAT, hal.HAL_IN)

#Output joint moment
h.newpin("moment1", hal.HAL_FLOAT, hal.HAL_OUT)
h.newpin("moment2", hal.HAL_FLOAT, hal.HAL_OUT)
h.newpin("moment3", hal.HAL_FLOAT, hal.HAL_OUT)
h.newpin("moment4", hal.HAL_FLOAT, hal.HAL_OUT)
h.newpin("moment5", hal.HAL_FLOAT, hal.HAL_OUT)
h.newpin("moment6", hal.HAL_FLOAT, hal.HAL_OUT)

h.ready()
try:
    while 1:

        positions = struc.Double_Vector()
        velocities = struc.Double_Vector()
        accelerates = struc.Double_Vector()

        positions = [h['pos1'], h['pos2'], h['pos3'], h['pos4'], h['pos5'], h['pos6']]
        velocities = [h['vel1']*3.1416/180, h['vel2']*3.1416/180, h['vel3']*3.1416/180, h['vel4']*3.1416/180, h['vel5']*3.1416/180, h['vel6']*3.1416/180]
        accelerates = [h['acc1']*3.1416/180, h['acc2']*3.1416/180, h['acc3']*3.1416/180, h['acc4']*3.1416/180, h['acc5']*3.1416/180, h['acc6']*3.1416/180]

        moments = struc.moments_cal(positions, velocities, accelerates)

        h['moment1'] = moments.mm1
        h['moment2'] = moments.mm2
        h['moment3'] = moments.mm3
        h['moment4'] = moments.mm4
        h['moment5'] = moments.mm5
        h['moment6'] = moments.mm6

except KeyboardInterrupt:
    raise SystemExit
